Enhancement: We can now set auth.server.prefix and auth.server.suffix…
icgc-dcc/dcc-id pull request #20
Opened 2018-11-20 17:46 UTC by KevinFHartmann

… to set the

scope prefix and suffix that we require for write access (ie. prefix: id, suffix: WRITE)
Enhancement: Our security configuration now works with values that are not
hard-coded at compile-time.

2018-11-20 17:47 UTC, KevinFHartmann commented
ok to test

2018-11-20 18:28 UTC, andricDu requested changes

2018-11-20 18:28 UTC, andricDu commented on dcc-id-server/src/main/conf/application.yml
> +    suffix: create.WRITE
why don't we just have the suffix as `WRITE`

so that the correct scope would be `id.WRITE`

2018-11-20 20:16 UTC, KevinFHartmann commented on dcc-id-server/src/main/conf/application.yml
> +    suffix: create.WRITE
That makes sense. :-)

2018-11-20 20:29 UTC, KevinFHartmann commented
ok to test

2019-03-05 17:37 UTC, KevinFHartmann commented
We will need this version of the id server to work with ego.

2019-03-06 16:08 UTC, andricDu approved these changes

2019-03-06 16:14 UTC, rtisma approved these changes

2019-03-06 16:15 UTC, merged